### ISSUE TITLE
Upload 1.1.0 to Maven repo

### ISSUE THREAD

**Issue by longbkiter07** [eclipse/paho.mqtt.android#112]
Since `https://repo.eclipse.org/content/repositories/paho-snapshots/` sometimes could not be connected (I got that issue twice, right now its happening), so please help us to upload latest android version to maven central so that we could not be blocked when developing.
Thanks

**Comment by nisrulz** [comment]
@longbkiter07 this is already been filed once under Issue https://github.com/eclipse/paho.mqtt.android/issues/96.

There is a certain procedure (here in Paho, they need credentials) that needs to be followed to publish it to Maven Central and it has already been initiated by the team managing this android library. 
Quoting @jpwsutton 
>In order to publish the Android service to maven central, we need to add the credentials to our Hudson Build server, this has been requested in this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=498122

**Comment by dmsherazi** [comment]
The issue is only with the snapshot version which is not on the maven repo.  and can be overcome if we use the aar file in the .gradle folder by following this [SO answer ](http://stackoverflow.com/a/23326397/1155507 )

You can get the cached version of the 1.1.1 Snapshot as of 31st July below
[org.eclipse.paho.android.service:1.1.1-SNAPSHOT
](https://github.com/dmsherazi/paho.mqtt.android/blob/master/org.eclipse.paho.android.service-1.1.1-SNAPSHOT.aar?raw=true)

**Comment by nisrulz** [comment]
@dmsherazi turns out I had [answered](http://stackoverflow.com/a/28816265/2745762) to the same question and its just below the accepted answer. 😄

**Comment by jpwsutton** [comment]
As we've now had a new release (1.1.1), I spent some time getting the builds working. Version 1.1.1 is now available on the OSSRH (Maven Central) http://repo1.maven.org/maven2/org/eclipse/paho/org.eclipse.paho.android.service/1.1.1/
