### ISSUE TITLE
Offline buffering not working on 1.1.0

### ISSUE THREAD

**Issue by dimparf** [eclipse/paho.mqtt.android#126]
Please fill out the form below before submitting, thank you!

- [ x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on: 23

## Description of Bug:
I am use Android Paho client library v1.1.0, QoS 2. My code for pub/sub:

```
mClient = new MqttAndroidClient(this, uri, clientId, new   MqttDefaultFilePersistence());
MqttConnectOptions conOpt = new MqttConnectOptions();

conOpt.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1);
conOpt.setCleanSession(true);
conOpt.setAutomaticReconnect(true);

mClient.setTraceEnabled(true);

mClient.setCallback(this);
mClient.setTraceCallback(this);

IMqttToken connectToken = mClient.connect(conOpt, null, this);
```

And offline buffering options:
```
@Override
public void onSuccess(IMqttToken iMqttToken) {
    this.disconnectedBufferOptions = new DisconnectedBufferOptions();
    this.disconnectedBufferOptions.setBufferEnabled(true);
    mClient.setBufferOpts(disconnectedBufferOptions);
    subscribe(topic);
}
```
Messages published to topic if the network is available, but if it disabled and enabled again offline messages not sending. How to correctly enable offline buffering option and send offline messages? 

Additional info: mClient.getBufferedMessageCount() after network disabled and publish message = 0

**Comment by jpwsutton** [comment]
Thanks for spotting this, I've had a play with the example code and can see this happening too.

Interestingly it seems that this bug only occurs when the phone has changed it's connection state and is no longer capable of accessing any data network.

If however, the phone is connected to the internet and the broker goes down, then the offline buffering functionality works as expected. I think this is because something in the Android library is not setting the Java client never enters the 'resting' state. I'll keep digging to see if I can figure out why...

**Comment by jpwsutton** [comment]
Cause: https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttConnection.java#L811

Looks like when the connection is lost due to a network status change, we just disconnect all connections completely. This will prevent the disconnected buffer from working. The fix should be fairly simple.

**Comment by miketran78727** [comment]
Is there a reason the Android client library wants to disconnect when connection is lost?  For other clients, such as Java, it is up to the application to call disconnect(), then close(), ...

**Comment by jpwsutton** [comment]
This was originally added I think by the initial author of the library, it was the Android services answer to automatic reconnect to cope with the changing network state that most phones experience. By calling disconnect, it allows the application to 'fail fast' instead of timing out. I don't think we can remove the existing functionality as that may affect some users, but I'll put a check in so that if we're using the java automatic reconnect functionality, we don't call this.

**Comment by jpwsutton** [comment]
The service will now only call disconnect() if automatic reconnect is not enabled, furthermore if automatic reconnect is enabled it will attempt to call reconnect() when the network changes to a state where the device can resume IP comms

**Comment by dimparf** [comment]
But this is not working. I am pull develop branch to my project, run code from this issue, but offline buffering not working correctly. If client is offline - messages not buffered and not sending after reconnect.

**Comment by jpwsutton** [comment]
Could you confirm this using the example client please? I've just tested this on my example client where It connected to iot.eclipse.org and I published a few messages that were delivered correctly, I then put the phone into airplane mode causing it to disconnect. After hitting publish a few times and getting confirmation that messages were being stored in the buffer, I disabled airplane mode and the client reconnected and sent the buffered messages.

Maybe try comparing your code to that of the example client to see if there is anything different that could cause your application to work correctly?

**Comment by dimparf** [comment]
@jpwsutton Yes, let's compare with you example, maybe I'm doing something wrong. Show me your example client code.

**Comment by jpwsutton** [comment]
https://github.com/eclipse/paho.mqtt.android/tree/develop/paho.mqtt.android.example

**Comment by dimparf** [comment]
@jpwsutton Hmm James, if I use 
mClient.publish(topic, message, qos, retained, null, this) method then OfflineBuffering not working, but if  mClient.publish(topic, mqttMessage) (as is your example, thanks!) it works.

**Comment by Lexycon** [comment]
Well,
I got the same issue like @dimparf, is this still an existing bug? 
I am using the latest snapshot [1.1.2-20170908](https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.android.service/1.1.2-SNAPSHOT/org.eclipse.paho.android.service-1.1.2-20170908.044047-5.jar)

**Comment by gantamk** [comment]
@Lexycon Lexycon, facing the same problem. did you find any fix for this. Thanks

**Comment by gantamk** [comment]
@jpwsutton jpwsutton, is your fix merged. We are facing same issue. If not can you give me your branch name, so we can try use it.  Thanks in advance

**Comment by Lexycon** [comment]
@gantamk nope, I didn't follow up on that issue. I used the way @dimparf mentioned:

```
MqttMessage message = new MqttMessage("Hallo".getBytes());
message.setQos(2);
mqttAndroidClient.publish("s/us/id", message);
```

**Comment by vikasvnaik** [comment]
@jpwsutton facing issue with storing messages in disconnect buffer when client is offline.Will is work with setting Qos 2? I'm not able to access example client code can u please give a update on this.
Thank You
