### ISSUE TITLE
MqttAndroidClient on a service

### ISSUE THREAD

**Issue by panagorn** [eclipse/paho.mqtt.android#157]
Hello i want to put MqttAndroidClient on a service because i do a lot of work on each message when it received and android some times shows not responding. 
 @Override
    public void messageArrived(String topic, MqttMessage message)
    }
Should i put MqttAndroidClient on a service or when a message arrived start an async task to to the job on each message?

**Comment by jpwsutton** [comment]
For best results, the Service should be used. Take a look at the example project here: https://github.com/eclipse/paho.mqtt.android/tree/master/paho.mqtt.android.example

**Comment by panagorn** [comment]
Yes, but in the example the MqttAndroidClient is not in a service

**Comment by jpwsutton** [comment]
https://github.com/eclipse/paho.mqtt.android/blob/master/paho.mqtt.android.example/src/main/AndroidManifest.xml#L32

**Comment by panagorn** [comment]
You have the service on the manifest and you also have MqttAndroidClient in the PahoExampleActivity. What i want is to have a service with MqttAndroidClient insite of it so that the messages come on the background

public class HelloService extends Service {
     MqttAndroidClient client;
}

**Comment by jpwsutton** [comment]
The MqttAndroidClient is backed up by the MqttService that does run in the background. You could always re-implement MqttAndroidClient if you wanted? You can see where we bind to the service here: https://github.com/eclipse/paho.mqtt.android/blob/develop/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttAndroidClient.java#L110

**Comment by Aeefire** [comment]
Hello. 

I have a similar problem to him, as I am also receiving quite frequent data. As your service, by default, sends out intents, which are then received by the MqttClient (which acts as a broadcast receiver), there is indeed, no way this happens not on the mainthread (by definition of Android's BroadcastReceivers). Furthermore, this also represents a lot of overhead etc. while still being good practice in the Android framework.

Now I tried to implement an async callback using a listener  / server binding which does not use the intent/broadcast mechanism by extending the MqttService class. HOWEVER, the critical method "callbackToActivity" is indeed package private. If this would be changed to public, we could implement a different behavior ourselves, which does not need Intents and BroadcastReceivers. 
Is it a possibility to rewrite this behavior on your side, or refactor it to make it more generic and overwritable by client applications ? 

Otherwise I am just gonna fork the library, which would be the less preferred option :)

Thanks in advance,
Clemens

**Comment by rafaelekol** [comment]
For async and network tasks we use Reactive approach RxJava. 
I also need to use Mqtt as service, to which I can listen, connect, disconnect and publish. I also like @Aeefire idea, to have more generic sample for Mqtt client.

**Comment by limitium** [comment]
Actually you can run MqttClient from your own service instead of Activity. But anyway I agree that MqttClient and MqttService must be more generalized and decoupled from each other and activity to use for instance EventBus instead of inefficient Intent mechanism

**Comment by chintan-mishra** [comment]
@rafaelekol can you show some code for the RxJava/RxAndroid approach?

**Comment by BuzzHari** [comment]
@Aeefire, how did you use the forked library in your code?
