### ISSUE TITLE
Error:Failed to resolve: org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by Gongcong** [eclipse/paho.mqtt.android#160]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

**Comment by jpwsutton** [comment]
I'm assuming this is because you cannot currently resolve repo.eclipse.org because the server is currently down. A bug has been raised to fix this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=508658
In the future could you please include more detail in your github issues, the template above is meant to be filled in to help us solve them as fast as possible 😉

**Comment by Gongcong** [comment]
@jpwsutton ，thanks for u help.
 Next time ,i will provide more detail.
