### ISSUE TITLE
How to have MQTT Client callback in background thread

### ISSUE THREAD

**Issue by rafaelekol** [eclipse/paho.mqtt.android#207]
In our app we can receive many messages via socket at once( ~ more than 200 messages in 3 seconds). And this freezes our apps UI. By digging MQTT client we think that problem lies in MqttClient callback, that works in Main Thread. Can we have callback in background thread, so heavy load won't affect UI?

```
mqttAndroidClient = new MqttAndroidClient(getApplicationContext(), serverUri, deviceId);        mqttAndroidClient.setCallback(new MqttCallbackExtended() {
@Override
 public void messageArrived(String topic, MqttMessage message) throws Exception {
            try {
                 Log.d(TAG, "messageArrived: " + new String(message.getPayload()));
                 dispatch(new String(message.getPayload()));
             } catch (Exception e) {
                    Log.e(TAG, "messageArrived error: ", e);
                }
            }
}
```

**Comment by rafaelekol** [comment]
We replaced  `registerReceiver` to use `Handler` running on different thread. This solved our problem with heavy load on UI thread

old one
```
private void registerReceiver(BroadcastReceiver receiver) {
		IntentFilter filter = new IntentFilter();
		filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
		LocalBroadcastManager.getInstance(myContext).registerReceiver(receiver, filter);
		receiverRegistered = true;
	}
```
new one
```
private void registerReceiver(BroadcastReceiver receiver) {
        if (handler == null) {
            HandlerThread handlerThread = new HandlerThread("MyNewThread");
            handlerThread.start();
            Looper looper = handlerThread.getLooper();
            handler = new Handler(looper);
        }
        IntentFilter filter = new IntentFilter();
        filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
        myContext.registerReceiver(receiver, filter, null, handler);
        receiverRegistered = true;
    }
```

**Comment by brspurri** [comment]
I'm running into the same problem. I implemented your fix, but the client does not appear to connect. At least the `messageArrived()` method is never fired. However, `messageArrived` **is** fired if I don't use a handler.

Did you have to make any additional changes outsied the `registerReceiver` method to ge this to work?

**Comment by riccardoch** [comment]
@rafaelekol I tried to add the same edit, but without success. The callbacks seem not working. Did you do other edits?

**Comment by riccardoch** [comment]
I solved this using **MqttAsyncClient** instead of **MqttAndroidClient**.

**Comment by sam0829** [comment]
Why it's labelled as "Question"? Was it really a matter of finding it out? I guess no. Because the OP's suggestion needs to modify code in your library & not an inbuilt way of handling this. Would really like to see the official or another way of doing this instead of modifying how we register the receiver.

**Comment by ainiyiwan** [comment]
@sam0829 Firstly, thank you so much, I did as what you said, and I solved my problem. I face a new problem, I don't know if you has faced. 
My problem is , Firstly my app will receive hundreds of mqtt messages in a second, so my message may come later then IOS sometimes. but if there are a small number of message, Android andr IOS will receive mqtt message in the same  time.
My English is poor, I dot't know if you understand what I have say. I am looking forward to your reply.

**Comment by sam0829** [comment]
@ainiyiwan I don't have an iOS version to compare with so I can't tell you anything on that :( Try to make a simple demo in Android and see the speed there may be?

**Comment by ainiyiwan** [comment]
@sam0829 Thank you so much! You are really very nice! I will try it!

**Comment by ainiyiwan** [comment]
@sam0829 when I receive more message per seconds, It delay more time. I think it's because of the library, 
It has alot of callbacks in it. I change the library again, now I can receive message faster, but I am not sure If I have really solve this problem. And this time I change alot of the library . Hi sam0829, I am looking for a software that we can use to communicate.. Do you have some software to recommend?
![0](https://user-images.githubusercontent.com/19484937/40219490-2fa24876-5aa8-11e8-9906-65d686b8b8cd.jpg)
![1](https://user-images.githubusercontent.com/19484937/40219498-367c070e-5aa8-11e8-908c-a61b35967a3a.png)
![2](https://user-images.githubusercontent.com/19484937/40219504-3ba6223c-5aa8-11e8-8f4d-5619fec784e0.jpg)

**Comment by ainiyiwan** [comment]
@sam0829 Do you use WeChat? In our country, we always use WeChat to communicate with each other.

**Comment by sam0829** [comment]
@ainiyiwan send me WeChat details on sandip.soni0892@gmail.com
I am also looking into this for fixing slow messaging issue.

**Comment by BuzzHari** [comment]
@rafaelekol  @ainiyiwan How do you modify the library and use it in your android project?

**Comment by alirezaTaheri** [comment]
I know it's too late but I want to say what did I do to solve the same problem, hope someone could use. :)
I have the same issue when my app opens and some messages arrive. and cause the UI stops for moments.I solve the problem by using @rafaelekol and @sam0829 solution. Indeed I made two changes in Paho Mqtt Library for use the global receiver instead of Local Receiver. 
It means use `context.registerReceiver()` and `context.sendBroadcast()`  instead of `localBroadcastManager.registerReceiver()` and `localBroadcastManager.sendBroadcast()` .
I replaced these in **MqttService.java** and **MqttAndroidClient.java** files.

But after days I received feedbacks of users about they have multiple unknown crashes in the app.
After I saw the logs, realized where the problem is. 
`E AndroidRuntime: android.app.RemoteServiceException: can't deliver broadcast
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
`
Then I searched the web and I guess the problem is the Android sometimes can't deliver broadcast.
and I read about the advantages of **LocalBroadcastManager** over Global version of it. (you can read more by search it)

When I saw myself do modifying the library, I decided to make more changes and use **RxJava** solution for Mqtt In-App-Messaging. So I created  **MqttEventBus.java** :

`public class MqttEventBus {
    public MqttEventBus() {
    }

    private PublishSubject<Intent> bus = PublishSubject.create();

    public void send(Intent intent) {
        bus.onNext(intent);
    }

    public Observable<Intent> toObservable() {
        return bus;
    }
}`

And make the following changes to **registerReceiver** method of **MqttAndroidClient** :
`public static MqttEventBus mqttEventBus;
	 private void registerReceiver(BroadcastReceiver receiver) {
		 IntentFilter filter = new IntentFilter();
		 filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
         mqttEventBus = new MqttEventBus();
         mqttEventBus.toObservable().observeOn(Schedulers.io()).subscribeOn(Schedulers.io()).subscribe(eventBusOnReceive());
         receiverRegistered = true;
	 }
public Consumer<Intent> eventBusOnReceive(){
        return new Consumer<Intent>() {
            @Override
            public void accept(Intent intent) throws Exception {
                Bundle data = intent.getExtras();
                String handleFromIntent = data
                        .getString(MqttServiceConstants.CALLBACK_CLIENT_HANDLE);
               //And everything is in the onReceive method in MqttAndroidClient....
....
}
        };
`
And changed **callbackToActivity** method of **MqttService.java** :
`void callbackToActivity(String clientHandle, Status status,
      Bundle dataBundle) {
    // Don't call traceDebug, as it will try to callbackToActivity leading
    // to recursion.
    final Intent callbackIntent = new Intent(
        MqttServiceConstants.CALLBACK_TO_ACTIVITY);
    if (clientHandle != null) {
      callbackIntent.putExtra(
          MqttServiceConstants.CALLBACK_CLIENT_HANDLE, clientHandle);
    }
    callbackIntent.putExtra(MqttServiceConstants.CALLBACK_STATUS, status);
    if (dataBundle != null) {
      callbackIntent.putExtras(dataBundle);
    }
    MqttAndroidClient.mqttEventBus.send(callbackIntent);
  }`

Until now I didn't receive any crash report.... It works and the UI is running smoothly and I think it has less overhead than broadcasts. Hope this helps...

**Comment by alirezaTaheri** [comment]
I know it's too late but I want to say what did I do to solve the same problem, hope someone could use. :)
I have the same issue when my app opens and some messages arrive. and cause the UI stops for moments.I solve the problem by using @rafaelekol and @sam0829 solution. Indeed I made two changes in Paho Mqtt Library for use the global receiver instead of Local Receiver. 
It means use `context.registerReceiver()` and `context.sendBroadcast()`  instead of `localBroadcastManager.registerReceiver()` and `localBroadcastManager.sendBroadcast()` .
I replaced these in **MqttService.java** and **MqttAndroidClient.java** files.

But after days I received feedbacks of users about they have multiple unknown crashes in the app.
After I saw the logs, realized where the problem is: 
```

E AndroidRuntime: android.app.RemoteServiceException: can't deliver broadcast
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

```
Then I searched the web and I guess the problem is the Android sometimes can't deliver broadcast.
and I read about the advantages of **LocalBroadcastManager** over Global version of it. (you can read more by search it)

When I saw myself do modifying the library, I decided to make more changes and use **RxJava** solution for Mqtt In-App-Messaging. So I created  **MqttEventBus.java** :

`public class MqttEventBus {
    public MqttEventBus() {
    }

    private PublishSubject<Intent> bus = PublishSubject.create();

    public void send(Intent intent) {
        bus.onNext(intent);
    }

    public Observable<Intent> toObservable() {
        return bus;
    }
}`

And make the following changes to **registerReceiver** method of **MqttAndroidClient** :
`public static MqttEventBus mqttEventBus;
	 private void registerReceiver(BroadcastReceiver receiver) {
		 IntentFilter filter = new IntentFilter();
		 filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
         mqttEventBus = new MqttEventBus();
         mqttEventBus.toObservable().observeOn(Schedulers.io()).subscribeOn(Schedulers.io()).subscribe(eventBusOnReceive());
         receiverRegistered = true;
	 }
public Consumer<Intent> eventBusOnReceive(){
        return new Consumer<Intent>() {
            @Override
            public void accept(Intent intent) throws Exception {
                Bundle data = intent.getExtras();
                String handleFromIntent = data
                        .getString(MqttServiceConstants.CALLBACK_CLIENT_HANDLE);
               //And everything is in the onReceive method in MqttAndroidClient....
....
}
        };
`
And changed **callbackToActivity** method of **MqttService.java** :
`void callbackToActivity(String clientHandle, Status status,
      Bundle dataBundle) {
    // Don't call traceDebug, as it will try to callbackToActivity leading
    // to recursion.
    final Intent callbackIntent = new Intent(
        MqttServiceConstants.CALLBACK_TO_ACTIVITY);
    if (clientHandle != null) {
      callbackIntent.putExtra(
          MqttServiceConstants.CALLBACK_CLIENT_HANDLE, clientHandle);
    }
    callbackIntent.putExtra(MqttServiceConstants.CALLBACK_STATUS, status);
    if (dataBundle != null) {
      callbackIntent.putExtras(dataBundle);
    }
    MqttAndroidClient.mqttEventBus.send(callbackIntent);
  }`

Until now I didn't receive any crash report.... It works and the UI is running smoothly and I think it has less overhead than broadcasts. Hope this helps...

**Comment by alirezaTaheri** [comment]
I know it's too late but I want to say what did I do to solve the same problem, hope someone could use. :)
I have the same issue when my app opens and some messages arrive. and cause the UI stops for moments.I solve the problem by using @rafaelekol and @sam0829 solution. Indeed I made two changes in Paho Mqtt Library for use the global receiver instead of Local Receiver. 
It means use `context.registerReceiver()` and `context.sendBroadcast()`  instead of `localBroadcastManager.registerReceiver()` and `localBroadcastManager.sendBroadcast()` .
I replaced these in **MqttService.java** and **MqttAndroidClient.java** files.

But after days I received feedbacks of users about they have multiple unknown crashes in the app.
After I saw the logs, realized where the problem is. 
```
E AndroidRuntime: android.app.RemoteServiceException: can't deliver broadcast
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

Then I searched the web and I guess the problem is the Android sometimes can't deliver broadcast.
and I read about the advantages of **LocalBroadcastManager** over Global version of it. (you can read more by search it)

When I saw myself do modifying the library, I decided to make more changes and use **RxJava** solution for Mqtt In-App-Messaging. So I created  **MqttEventBus.java** :

```
public class MqttEventBus {
    public MqttEventBus() {
    }

    private PublishSubject<Intent> bus = PublishSubject.create();

    public void send(Intent intent) {
        bus.onNext(intent);
    }

    public Observable<Intent> toObservable() {
        return bus;
    }
}
```

And make the following changes to **registerReceiver** method of **MqttAndroidClient** :
```
public static MqttEventBus mqttEventBus;
	 private void registerReceiver(BroadcastReceiver receiver) {
		 IntentFilter filter = new IntentFilter();
		 filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
         mqttEventBus = new MqttEventBus();
         mqttEventBus.toObservable().observeOn(Schedulers.io()).subscribeOn(Schedulers.io()).subscribe(eventBusOnReceive());
         receiverRegistered = true;
	 }
public Consumer<Intent> eventBusOnReceive(){
        return new Consumer<Intent>() {
            @Override
            public void accept(Intent intent) throws Exception {
                Bundle data = intent.getExtras();
                String handleFromIntent = data
                        .getString(MqttServiceConstants.CALLBACK_CLIENT_HANDLE);
               //And everything is in the onReceive method in MqttAndroidClient....
....
}
        };
```

And changed **callbackToActivity** method of **MqttService.java** :
```
void callbackToActivity(String clientHandle, Status status,
      Bundle dataBundle) {
    // Don't call traceDebug, as it will try to callbackToActivity leading
    // to recursion.
    final Intent callbackIntent = new Intent(
        MqttServiceConstants.CALLBACK_TO_ACTIVITY);
    if (clientHandle != null) {
      callbackIntent.putExtra(
          MqttServiceConstants.CALLBACK_CLIENT_HANDLE, clientHandle);
    }
    callbackIntent.putExtra(MqttServiceConstants.CALLBACK_STATUS, status);
    if 
```(dataBundle != null) {
      callbackIntent.putExtras(dataBundle);
    }
    MqttAndroidClient.mqttEventBus.send(callbackIntent);
  }

Until now I didn't receive any crash report.... It works and the UI is running smoothly and I think it has less overhead than broadcasts. Hope this helps...

**Comment by alirezaTaheri** [comment]
I know it's too late but I want to say what did I do to solve the same problem, hope someone could use. :)
I have the same issue when my app opens and some messages arrive. and cause the UI stops for moments.I solve the problem by using @rafaelekol and @sam0829 solution. Indeed I made two changes in Paho Mqtt Library for use the global receiver instead of Local Receiver. 
It means use `context.registerReceiver()` and `context.sendBroadcast()`  instead of `localBroadcastManager.registerReceiver()` and `localBroadcastManager.sendBroadcast()` .
I replaced these in **MqttService.java** and **MqttAndroidClient.java** files.

But after days I received feedbacks of users about they have multiple unknown crashes in the app.
After I saw the logs, realized where the problem is. 
```
E AndroidRuntime: android.app.RemoteServiceException: can't deliver broadcast
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

Then I searched the web and I guess the problem is the Android sometimes can't deliver broadcast.
and I read about the advantages of **LocalBroadcastManager** over Global version of it. (you can read more by search it)

When I saw myself do modifying the library, I decided to make more changes and use **RxJava** solution for Mqtt In-App-Messaging. So I created  **MqttEventBus.java** :

```
public class MqttEventBus {
    public MqttEventBus() {
    }

    private PublishSubject<Intent> bus = PublishSubject.create();

    public void send(Intent intent) {
        bus.onNext(intent);
    }

    public Observable<Intent> toObservable() {
        return bus;
    }
}
```

And make the following changes to **registerReceiver** method of **MqttAndroidClient** :
```
public static MqttEventBus mqttEventBus;
	 private void registerReceiver(BroadcastReceiver receiver) {
		 IntentFilter filter = new IntentFilter();
		 filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
         mqttEventBus = new MqttEventBus();
         mqttEventBus.toObservable().observeOn(Schedulers.io()).subscribeOn(Schedulers.io()).subscribe(eventBusOnReceive());
         receiverRegistered = true;
	 }

public Consumer<Intent> eventBusOnReceive(){
        return new Consumer<Intent>() {
            @Override
            public void accept(Intent intent) throws Exception {
                Bundle data = intent.getExtras();
                String handleFromIntent = data
                        .getString(MqttServiceConstants.CALLBACK_CLIENT_HANDLE);
               //And everything is in the onReceive method in MqttAndroidClient....
               ....
}
        };
```

And changed **callbackToActivity** method of **MqttService.java** :
```
void callbackToActivity(String clientHandle, Status status,
      Bundle dataBundle) {
    // Don't call traceDebug, as it will try to callbackToActivity leading
    // to recursion.
    final Intent callbackIntent = new Intent(
        MqttServiceConstants.CALLBACK_TO_ACTIVITY);
    if (clientHandle != null) {
      callbackIntent.putExtra(
          MqttServiceConstants.CALLBACK_CLIENT_HANDLE, clientHandle);
    }
    callbackIntent.putExtra(MqttServiceConstants.CALLBACK_STATUS, status);
    if (dataBundle != null) {
      callbackIntent.putExtras(dataBundle);
    }
    MqttAndroidClient.mqttEventBus.send(callbackIntent);
  }
```

Until now I didn't receive any crash report.... It works and the UI is running smoothly and I think it has less overhead than broadcasts. Hope this helps...

**Comment by alirezaTaheri** [comment]
I know it's too late but I want to say what I did to solve the same problem, hope someone could use. :)
I have the same issue when my app opens and some messages arrive. and cause the UI stops for moments.I solve the problem by using @rafaelekol and @sam0829 solution. Indeed I made two changes in Paho Mqtt Library for use the global receiver instead of Local Receiver. 
It means use `context.registerReceiver()` and `context.sendBroadcast()`  instead of `localBroadcastManager.registerReceiver()` and `localBroadcastManager.sendBroadcast()` .
I replaced these in **MqttService.java** and **MqttAndroidClient.java** files.

But after days I received feedbacks of users about they have multiple unknown crashes in the app.
After I saw the logs, realized where the problem is. 
```
E AndroidRuntime: android.app.RemoteServiceException: can't deliver broadcast
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

Then I searched the web and I guess the problem is the Android sometimes can't deliver broadcast.
and I read about the advantages of **LocalBroadcastManager** over Global version of it. (you can read more by search it)

When I saw myself do modifying the library, I decided to make more changes and use **RxJava** solution for Mqtt In-App-Messaging. So I created  **MqttEventBus.java** :

```
public class MqttEventBus {
    public MqttEventBus() {
    }

    private PublishSubject<Intent> bus = PublishSubject.create();

    public void send(Intent intent) {
        bus.onNext(intent);
    }

    public Observable<Intent> toObservable() {
        return bus;
    }
}
```

And make the following changes to **registerReceiver** method of **MqttAndroidClient** :
```
public static MqttEventBus mqttEventBus;
	 private void registerReceiver(BroadcastReceiver receiver) {
		 IntentFilter filter = new IntentFilter();
		 filter.addAction(MqttServiceConstants.CALLBACK_TO_ACTIVITY);
         mqttEventBus = new MqttEventBus();
         mqttEventBus.toObservable().observeOn(Schedulers.io()).subscribeOn(Schedulers.io()).subscribe(eventBusOnReceive());
         receiverRegistered = true;
	 }

public Consumer<Intent> eventBusOnReceive(){
        return new Consumer<Intent>() {
            @Override
            public void accept(Intent intent) throws Exception {
                Bundle data = intent.getExtras();
                String handleFromIntent = data
                        .getString(MqttServiceConstants.CALLBACK_CLIENT_HANDLE);
               //And everything is in the onReceive method in MqttAndroidClient....
               ....
}
        };
```

And changed **callbackToActivity** method of **MqttService.java** :
```
void callbackToActivity(String clientHandle, Status status,
      Bundle dataBundle) {
    // Don't call traceDebug, as it will try to callbackToActivity leading
    // to recursion.
    final Intent callbackIntent = new Intent(
        MqttServiceConstants.CALLBACK_TO_ACTIVITY);
    if (clientHandle != null) {
      callbackIntent.putExtra(
          MqttServiceConstants.CALLBACK_CLIENT_HANDLE, clientHandle);
    }
    callbackIntent.putExtra(MqttServiceConstants.CALLBACK_STATUS, status);
    if (dataBundle != null) {
      callbackIntent.putExtras(dataBundle);
    }
    MqttAndroidClient.mqttEventBus.send(callbackIntent);
  }
```

Until now I didn't receive any crash report.... It works and the UI is running smoothly and I think it has less overhead than broadcasts. Hope this helps...

**Comment by Someshwari-Chaayos** [comment]
Hello @alirezaTaheri ,

what is **PublishSubject**  in the code mentioned above. Is the crashing issue is resolved using **MqttEventBus** ?

**Comment by Somu5050** [comment]
Hello **@alirezaTaheri** ,

what is **PublishSubject** in the code mentioned above. Is the crashing issue is resolved using **MqttEventBus** ?

**Comment by alirezaTaheri** [comment]
Hi @Somu5050 
Sorry for late response. Yes the crashing issue is completely over now.
The `PublishSubject` class as I mentioned above is in **RxJava** package. You can find it's doc in [here](http://reactivex.io/RxJava/javadoc/io/reactivex/subjects/PublishSubject.html).
Besides this, you can benefit a lot from playing with **RxJava** components.
Have fun...
