### ISSUE TITLE
 how to implement MqttAndroidClient reconnects

### ISSUE THREAD

**Issue by liqinghua188** [eclipse/paho.mqtt.android#65]
Now I need to implement the requirement that MqttAndroidClient reconnects when mqtt connection lost.

There are two ways:

* make the MqttConnection reconnect method visible to MqttAndroidClient so that invoking reconnect method when connetion lost 

* use MqttAndroidClient connect method directly, however, it need to remove registerReceiver(MqttAndroidClient.this) method when the mqttService is not null to protect from registering  more than once. At present, I haven't found what the purpose of registerReceiver is when the mqttService is not null. 

codes are as following:
	
	public IMqttToken connect(MqttConnectOptions options, Object userContext,
				IMqttActionListener callback) throws MqttException {
				
			.......
	
			pool.execute(new Runnable() {
				@Override
				public void run() {
					doConnect();
	
					registerReceiver(MqttAndroidClient.this);		// the second way need to remove this line
				}
	});
			............
	}

Is there any suggestions??

**Comment by jpwsutton** [comment]
@liqinghua188 We've recently delivered the Automatic Reconnect & Offline buffering functionality into the Android client so that you don't have to develop this functionality yourself. Its not been built into our snapshot yet, but once it is you'll be able to enable it by setting ```setAutomaticReconnect``` on the ```MqttConnectOptions``` to ```true```.

A full snapshot build should be coming soon. Once it is, I'll comment on this issue for you.

**Comment by jasonrogena** [comment]
Hi @jpwsutton has this feature been added to a snapshot yet?

**Comment by jpwsutton** [comment]
Apologies! yes, the functionality is in the 1.0.3-SNAPSHOT versions, and will be in the released library next month

**Comment by jasonrogena** [comment]
Funny, but is 1.0.3-SNAPSHOT stable enough to bundle in production on my side ;)?

**Comment by jpwsutton** [comment]
Up to you really, as of today the current snapshot is what will be built as the released version as we've got a freeze on contributions for now. Unless any significant bugs are discovered I doubt that there will be any changes between now and then. Neon is due to be released on June the first, so I guess it depends on whether you can wait that long?
